### ISSUE TITLE
Doing a release build fails

### ISSUE THREAD

**Issue by ueman** [NPadrutt/MoneyManager#297]
I'm not able to do a release build. It says "Symbole für das Modul "MoneyManager.Tasks.TransactionsWp.winmd" wurden nicht geladen.
And if you ignore it you can't start the app.

**Comment by NPadrutt** [comment]
Is the task project in the tasks folder loaded?
I can build aswell in VS 2013 and 2015.

**Comment by NPadrutt** [comment]
ah, just got it aswell :D

**Comment by ueman** [comment]
it's really weird because a debug build builds just fine.

**Comment by NPadrutt** [comment]
I found something. The thing is associated with the "Just My Code" setting for debugging. This leads to issues with the optimiziation who is applied for release builds and therefore they warn you with this message. You can disable this setting and all should be fine. What it means exactly to turn it on or off is explained in this article: 
http://blogs.msdn.com/b/zainnab/archive/2010/10/25/understanding-just-my-code.aspx

**Comment by ueman** [comment]
Yeah, I did disable it and the app didn't correctly launch and crashed at the start. However it could be an error I did somewhere. I have to recheck this tomorrow.

**Comment by NPadrutt** [comment]
mh. okey. i'll check that

**Comment by NPadrutt** [comment]
Good that you saw that. It seems the build is broken aswell.

**Comment by NPadrutt** [comment]
this is the message who I get in the output.. But coulndn't find much to it up to now..

Exception thrown: 'System.Resources.MissingManifestResourceException' in mscorlib.ni.dll
Exception thrown: 'System.Resources.MissingManifestResourceException' in WinRTXamlToolkit.Controls.DataVisualization.ni.DLL
Exception thrown: 'Windows.UI.Xaml.Markup.XamlParseException' in MoneyManager.WindowsPhone.ni.EXE
WinRT information: Cannot add instance of type '%0' to a collection of type '%1'. [Line: 25 Position: 33]
The program '[5356] MoneyManager.WindowsPhone.exe' has exited with code -1073741189 (0xc000027b).

**Comment by ueman** [comment]
this fixes the broken build:
https://github.com/ueman/MoneyManager/commit/36b2c31571b61cd1f70021716f99983fb9a2d98d
explanation here:
http://stackoverflow.com/questions/15596813/winrt-xaml-toolkit-column-series-error

I just can't wrap my head around it. Why does it build a debug build just fine?

**Comment by NPadrutt** [comment]
yeah, thats odd

**Comment by NPadrutt** [comment]
I commited your fixes. Thanks for the research!
